# This is a basic workflow to help you get started with Actions

name: ActionsWorkFlow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out 
        uses: actions/checkout@v3

      - name: setting up node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18"
           
      - name: Installing dependencies
        run: npm i

      - name: Building
        run: npm run build:prod

      - name: Deploying
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      
